### ISSUE TITLE
Bug: offset calculation might result in invalid argument

### ISSUE THREAD

**Issue by samip5** [beevik/ntp#48]
I think that the commit a393ae881c97d48a5b6b6ac490f278a29c06e733 broke RPi4 support.

The only diff related to NTP is https://github.com/beevik/ntp/compare/v1.3.1...v1.4.2 which suggest the commit above as the possible culprit.

It doesn't have an RTC on-board, and this is somewhat related to https://github.com/siderolabs/talos/issues/8828

**Comment by beevik** [comment]
I don't have a raspberry pi. Can you be more specific about what you mean when you say RPi4 support broke?

**Comment by beevik** [comment]
@smira 

So in investigating this problem further, I think your fix may not have addressed the actual issue, which is that the 64-bit NTP timestamp rolls over in the year 2036. It seems there is no way for `toNtpTime` to calculate a correct 64-bit timestamp for any date beyond that year.

For instance, in your `TestOfflineOffsetCalculationNegativeBig` unit test, we have the following line of code:

```go
rec := toNtpTime(serverNow)
```

This is calculating a value of `0x1480088000000000` when it should actually be `0x11480088000000000`.  The most significant bit was lost due to there not being enough bits to represent the number of elapsed nanoseconds since 1900.

I'm not entirely sure what the proper fix is, but I am curious to know your reasoning for why you believe the fix you submitted solves the problem.

**Comment by beevik** [comment]
OK, I understand better now why your solution works. Your solution takes advantage of the integer overflow/underflow caused by subtracting a rolled-over 64-bit integer from a non-rolled-over 64-bit integer.

However, I am not sure why your `beevik/ntp` fix would cause problems in the talos library on RPi4 devices. Perhaps there is some other issue.  I have no familiarity with talos.

**Comment by samip5** [comment]
> I don't have a raspberry pi. Can you be more specific about what you mean when you say RPi4 support broke?

The following snippet is from before the offset calculation PR (Talos 1.7.2):
```
[talos] adjusting time (jump) by 476956h13m42.710965835s via 162.159.200.1, state TIME_OK, status STA_NANO {"component": "controller-runtime", "controller": "time.SyncController"}
01/01/1970 02:00:51
[talos] adjusting time (slew) by -3.356409ms via 162.159.200.1, state TIME_OK, status STA_PLL | STA_NANO {"component": "controller-runtime", "controller": "time.SyncController"} 
```

After (Talos 1.7.3):
```
[630.925602] [talos] adjusting time (jump) by -119568h45m14.6261680059s via 162.159.200.123, state TIME_UNKNOWN, status , error was invalid argument {“component”: “controller-runtime”, “controller”: “time.SyncController”}
[630.947595] [talos] error adjusting time {“component”: “controller-runtime”, “controller”: “time.SyncController”, “error”: “invalid argument”}
[662.991514] [talos] adjusting time (jump) by -119568h45m14.636339687s via 162.159.200.123, state TIME_UNKNOWN, status , error was invalid argument {“component”: “controller-runtime”, “controller”: “time.SyncController”}
[663.014009] [talos] error adjusting time {“component”: “controller-runtime”, “controller”: “time.SyncController”, “error”: “invalid argument”}
[695.052468] [talos] adjusting time (jump) by -119568h45m14.6394740042s via 162.159.200.123, state TIME_UNKNOWN, status , error was invalid argument {“component”: “controller-runtime”, “controller”: “time.SyncController”}
[695.075093] [talos] error adjusting time {“component”: “controller-runtime”, “controller”: “time.SyncController”, “error”: “invalid argument”}
```

The only difference related to NTP seems to be update from `github.com/beevik/ntp v1.3.1` to `github.com/beevik/ntp v1.4.2` which doesn't seem like having much changed except for the commit I referenced.

**Comment by beevik** [comment]
@samip5 If you're able to build talos from scratch, can you try the following from the talos source code directory:

```go get github.com/beevik/ntp@a393ae8```

This should pull a patched version of the ntp package.  I am curious to know if it fixes your issue.

**Comment by beevik** [comment]
> The only difference related to NTP seems to be update from github.com/beevik/ntp v1.3.1 to github.com/beevik/ntp v1.4.2 which doesn't seem like having much changed except for the commit I referenced.

Ah, I think you're right. I'm pretty sure I know what's going on.

You mentioned that the RPi has no real-time clock. That means the first time it syncs, it's making a very large adjustment. The new offset calculation takes the average of two differences, each of which is very large.  The averaging of two values, a and b, each of which is large, is leading to a 64-bit integer overflow, which results in a negative value for the offset.

We'll need to compute the average in a way that doesn't overflow.

**Comment by beevik** [comment]
Ok I just pushed a new commit to fix this bug:  https://github.com/beevik/ntp/commit/235effe749df8cdf5d59e833f041313f2c1389e9

There is a new release (v1.4.3) to go with it.

**Comment by samip5** [comment]
It seems that in the future, the Pi4 having no real-time clock is starting to become a larger issue, but glad you worked it out. I'm building talos from scratch atm.

**Comment by smira** [comment]
@beevik thanks for fixing it and sorry I should have added more tests there.

**Comment by beevik** [comment]
@samip5 Now that a new version of talos has been released, can you confirm that the bug is fixed? If it is, please feel free to close the issue.

Thanks for the bug report.

**Comment by samip5** [comment]
Yes, it seems to work now. Thanks. :)
